client_config_backend: file
client_config:
    client_id: 965057209307-6jf267gp361tug7jra8td3t4mvvg56ld.apps.googleusercontent.com
    client_secret: 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

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
    - https://www.googleapis.com/auth/drive